name: Lint commits on push

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check if Husky is installed
        id: husky-check
        run: echo ::set-output name=installed::$(npm list --depth=0 | grep husky)
      - name: Install Husky
        if: steps.husky-check.outputs.installed == ''
        run: npm install husky --save-dev
      - name: active les hooks
        run: npx husky install
      - name: Ajout script
        run: npm run-script prepare
      - name: Install commitlint
        run: npm install @commitlint/cli @commitlint/config-conventional --save-dev
      - name: Ajout hook
        run : npx husky add .husky/commit-msg  "npx --no -- commitlint --edit ${1}"