name: GitFlow Workflow

on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify commit messages on dev
        if: github.ref == 'refs/heads/dev' # Spécifie que cette étape ne sera exécutée que lorsque le push est effectué sur la branche dev
        uses: wagoid/commitlint-github-action@v4 # Utilise l'action commitlint-action pour vérifier que les messages de commit sur la branche dev sont bien organisés
        with:
          args: "--config=config/commitlint.config.js" # Spécifie le chemin du fichier de configuration commitlint.config.js utilisé pour valider les messages de commit

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Lint code
        run: npm run lint

      - name: Test code
        run: npm test

      - name: Commit changes
        run: |
          git add .
          git commit -m "Test"
          git push