name: GitFlow Workflow

on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: ./API_Webshop # Permet de spécifier le répertoire de travail
        run: npm install

      - name: Test code
        working-directory: ./API_Webshop # Permet de spécifier le répertoire de travail
        run: npm test

      - name: Upload artifact
        uses: actions/upload-artifact@v2 # Utilise l'action upload-artifact pour télécharger l'artefact de construction (ici le dossier src) sur le serveur GitHub
        with:
          name: build # Spécifie le nom de l'artefact qu'on télécharge
          path: src #  Spécifie le chemin de l'artefact qu'on télécharge

      - name: Commit changes
        run: |
          git config --global user.email "quentin.quero22@gmail.com"
          git config --global user.name "QuentinQ22"
          git fetch --all
          git checkout main
          git pull
          git merge origin/dev --no-edit
          git push origin
