name: Lint commits on push

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: ./API_Webshop # Permet de spécifier le répertoire de travail
        run: npm install
      - name: Install commitlint
        working-directory: ./API_Webshop
        run: npm install --save-dev @commitlint/cli @commitlint/config-conventional
      - name: Lint commits
        working-directory: ./API_Webshop # Permet de spécifier le répertoire de travail
        run: npm run commitmsg