name: Lint commits on push

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install husky
        run: npm install husky --save-dev
      - name: active les hooks
        run: npx husky install
      - name: Ajout script
        run: npm set-script prepare "husky install"
      - name: Install dependencies
        working-directory: ./API_Webshop
        run: npm install
      - name: Install commitlint
        run: npm install @commitlint/cli @commitlint/config-conventional --save-dev
      - name: Ajout hook
        run : npx husky add .husky/commit-msg  "npx --no -- commitlint --edit ${1}"