name: Lint commits on push

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: ./API_Webshop
        run: npm install
      - name: Install commitlint
        working-directory: ./API_Webshop
        run: npm install @commitlint/cli @commitlint/config-conventional --save-dev
      - name: Lint commits
        working-directory: ./API_Webshop
        run: |
          git log --format=%s ${{ github.event.before }}..${{ github.event.after }}
          npx commitlint --from ${{ github.event.before }} --to ${{ github.event.after }}